import { AppSettings, Asset, RiskEntry } from "../types/grc";

const now = new Date().toISOString();

export const demoAssets: Asset[] = [
  {
    id: "asset-ad-server",
    name: "Active Directory Server",
    type: "Hardware",
    criticality: 3,
    createdAt: now,
  },
  {
    id: "asset-erp-app",
    name: "ERP Application",
    type: "Software",
    criticality: 3,
    createdAt: now,
  },
  {
    id: "asset-pii-db",
    name: "Student PII Database",
    type: "Data",
    criticality: 3,
    createdAt: now,
  },
  {
    id: "asset-it-admin",
    name: "IT Administrator Account",
    type: "People",
    criticality: 2,
    createdAt: now,
  },
  {
    id: "asset-email-gateway",
    name: "Email Security Gateway",
    type: "Software",
    criticality: 2,
    createdAt: now,
  },
];

export const demoRisks: RiskEntry[] = [
  {
    id: "risk-ransomware-ad",
    assetId: "asset-ad-server",
    threat: "Ransomware Infection",
    vulnerability: "Legacy SMB configuration",
    likelihood: 4,
    impact: 5,
    inherentRisk: 20,
    treatmentStrategy: "Mitigate",
    control: "Endpoint Detection & Response (EDR)",
    residualLikelihood: 2,
    residualImpact: 4,
    residualRisk: 8,
    status: "In Treatment",
    createdAt: now,
  },
  {
    id: "risk-sql-injection-erp",
    assetId: "asset-erp-app",
    threat: "SQL Injection",
    vulnerability: "Insufficient input validation",
    likelihood: 3,
    impact: 5,
    inherentRisk: 15,
    treatmentStrategy: "Mitigate",
    control: "Parameterized queries + WAF",
    residualLikelihood: 2,
    residualImpact: 4,
    residualRisk: 8,
    status: "In Treatment",
    createdAt: now,
  },
  {
    id: "risk-data-leak-pii",
    assetId: "asset-pii-db",
    threat: "Unauthorized Data Exfiltration",
    vulnerability: "Weak access reviews",
    likelihood: 3,
    impact: 5,
    inherentRisk: 15,
    treatmentStrategy: "Transfer",
    status: "Open",
    createdAt: now,
  },
  {
    id: "risk-phishing-admin",
    assetId: "asset-it-admin",
    threat: "Credential Phishing",
    vulnerability: "No phishing simulation program",
    likelihood: 4,
    impact: 4,
    inherentRisk: 16,
    treatmentStrategy: "Mitigate",
    control: "MFA + security awareness training",
    residualLikelihood: 2,
    residualImpact: 3,
    residualRisk: 6,
    status: "In Treatment",
    createdAt: now,
  },
  {
    id: "risk-email-downtime",
    assetId: "asset-email-gateway",
    threat: "Service Outage",
    vulnerability: "Single-zone deployment",
    likelihood: 2,
    impact: 3,
    inherentRisk: 6,
    treatmentStrategy: "Accept",
    status: "Open",
    createdAt: now,
  },
  {
    id: "risk-shadow-it",
    assetId: "asset-erp-app",
    threat: "Unapproved SaaS Usage",
    vulnerability: "Lack of cloud governance policy",
    likelihood: 3,
    impact: 3,
    inherentRisk: 9,
    treatmentStrategy: "Avoid",
    status: "Open",
    createdAt: now,
  },
];

export const demoSettings: AppSettings = {
  orgName: "CampusTech Services",
  riskAppetite: 15,
  framework: "ISO 27005",
};
